version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      minors:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    assignees:
      - till
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      action-deps:
        patterns:
          - "*"
    assignees:
      - till
